### ISSUE TITLE
mb move it to module ADXL_CTRL description 

### ISSUE THREAD

**Issue by MikitaChabatarovich** [WlodekLipski/Adxl_vhdl#8]
https://github.com/WlodekLipski/Adxl_vhdl/blob/e79c2905e2724ae957b09880b8e7a8bf4d6ce6ac/Ucisw/Ucisw.tex#L519

**Comment by WlodekLipski** [comment]
It's describe the above code. From my point of view it suits well.

**Comment by MikitaChabatarovich** [comment]
so maybe it better move to top of the code

**Comment by WlodekLipski** [comment]
Accepted.
